### ISSUE TITLE
Release executables for the latest version

### ISSUE THREAD

**Issue by martymarty004** [tasmota/decode-config#45]
### Is your feature request related to a problem? Please describe

Hello, I run in a Windows x64 environment and I used a script to back up my Tasmota devices with decode-config.
When a new version was released, I would simply replace the binary file with the newer version, but this time you didn't release the executable builds of the decode-config tool.

### Describe the solution you'd like

I'd prefer if you kept releasing decode-config with the binary files included in the package.

**Comment by curzon01** [comment]
Basically the binaries are not really binaries, but packages put together with a program named pyinstaller. Unfortunately, pyinstaller does not allow cross-platform creation, so that a virtual machine must be started for each platform for each binary creation in order to create a single binary there with pyinstaller.

Since v11.0.0, the release is published as a pypi package, which serves the same purpose as an exe that was created with a lot of effort.

Binaries will no longer be published because the creation is very time consuming and a process that cannot be automated.

To install decode-config [install python](https://www.python.org/downloads/windows/) for your platform and exec `python -m pip install decode-config` - then you can use `decode-config.py` the same way as you used the binary.
