### ISSUE TITLE
decode-config behind a proxy ERROR 10 (@3892): Device did not respond properly

### ISSUE THREAD

**Issue by defaliz** [tasmota/decode-config#55]
Hi,
i try to convert to json may tasmota device..
url is 
http://login:passwd@X.X.X.X/my_device/

this url works fine in a browser...
but when i use decode-config like this :
python3 decode-config.py --source http://login:passwd@X.X.X.X/my_device/  --json-indent 2 > conf_my_device.json
i have this error :
ERROR 10 (@3892): Device did not respond properly
i use a proxy and login passwd for proxy nginx and this is not tasmota webserver login...
is it possible to use decode-config with a proxy ?
regards

**Comment by curzon01** [comment]
Use the optional parameters `--username` and `--password`

see also [HTTP connection (Online)](https://github.com/tasmota/decode-config#http-connection-online) and [Obsolete source parameters](https://github.com/tasmota/decode-config#obsolete-source-parameters):

use `--backup-file` instead of redirect all output, it does the same but errors are printed on display and will not part of your redireected file. When still want to use redirection, only output stdout to the file, not stdout and stderr:
 
`python3 decode-config.py --source http://x.x.x.x/my_device/ --username login --password passwd --json-indent 2 --backup-file conf_my_device.json`

**Comment by defaliz** [comment]
thanks for reply
same error with your line..
Device did not respond properly, maybe Tasmota webserver admin mode is disabled (WebServer 2)
a curl command works fine 
it is not necessary to enable admin mode on tasmota device ?

**Comment by curzon01** [comment]
admin mode is mandatory
